### ISSUE TITLE
Do you know how to compute when number of samples is large ?

### ISSUE THREAD

**Issue by CoinCheung** [sassoftware/kernel-pca-sample-code#1]
Hi,

I noticed that the kpca method uses dot product matrix between samples rather than dimensions of naive pca method. That means when the number of samples gets large, the matrix requires more memory, which will hinder the application of the method to processing large datasets. Do you know how to handle this problem ?

**Comment by arinchau** [comment]
HI @CoinCheung ,
SAS's implementation of KPCA allows the use of Nystrom approximation to handle large cases. Please take a look at https://github.com/sassoftware/kernel-pca-sample-code/blob/master/visualization_example.sas for an example.

Hope this helps.
--Arin Chaudhuri

**Comment by arinchau** [comment]
Sorry @CoinCheung ,
I meant this example https://github.com/sassoftware/kernel-pca-sample-code/blob/master/letter_recognition_example.sas . Please take a look at all the comments in the example.

--Arin Chaudhuri
